// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        // Same Firebase app as macOS (bundle id matches). Re-run FlutterFire with
        // --platforms=ios,macos if you need separate iOS native config files.
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbPXlflCVYlcGZYzSxdHiENKCkYu2QZuc',
    appId: '1:737938045380:ios:33a1fd21ab07af5ff48c91',
    messagingSenderId: '737938045380',
    projectId: 'projectflo-e99c6',
    storageBucket: 'projectflo-e99c6.firebasestorage.app',
    iosBundleId: 'com.example.captionWriterFlutter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbPXlflCVYlcGZYzSxdHiENKCkYu2QZuc',
    appId: '1:737938045380:ios:33a1fd21ab07af5ff48c91',
    messagingSenderId: '737938045380',
    projectId: 'projectflo-e99c6',
    storageBucket: 'projectflo-e99c6.firebasestorage.app',
    iosBundleId: 'com.example.captionWriterFlutter',
  );
}
